"""update_for_theses

Revision ID: 186c5830e2c2
Revises: 499c6ba0c8a9
Create Date: 2016-11-30 19:46:14.590205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '186c5830e2c2'
down_revision = '499c6ba0c8a9'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('theses', sa.Column('publication_date', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('theses', 'publication_date')
    ### end Alembic commands ###
