"""change column name

Revision ID: 3da80373e7ab
Revises: b6b10c57992e
Create Date: 2016-11-26 16:18:58.750800

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3da80373e7ab'
down_revision = 'b6b10c57992e'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('filename', sa.String(length=64), nullable=True))
    op.drop_column('company', 'comment')
    op.add_column('competitions', sa.Column('filename', sa.String(length=64), nullable=True))
    op.drop_column('competitions', 'comment')
    op.drop_column('patent', 'commet')
    op.drop_column('theses', 'comment')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('theses', sa.Column('comment', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('patent', sa.Column('commet', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('competitions', sa.Column('comment', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('competitions', 'filename')
    op.add_column('company', sa.Column('comment', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('company', 'filename')
    ### end Alembic commands ###
