"""add created_time

Revision ID: 499c6ba0c8a9
Revises: 55d3df24d613
Create Date: 2016-11-28 15:35:41.766680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '499c6ba0c8a9'
down_revision = '55d3df24d613'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submit_history', sa.Column('submit_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submit_history', 'submit_date')
    ### end Alembic commands ###
