"""update models date

Revision ID: 8425c4ccc72a
Revises: e3664d3a8c43
Create Date: 2016-11-25 20:52:31.583560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8425c4ccc72a'
down_revision = 'e3664d3a8c43'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('competitions_ibfk_1', 'competitions', type_='foreignkey')
    op.add_column('theses', sa.Column('comment', sa.String(length=64), nullable=True))
    op.add_column('theses', sa.Column('dangci', sa.String(length=64), nullable=True))
    op.add_column('theses', sa.Column('filename', sa.String(length=64), nullable=True))
    op.add_column('theses', sa.Column('publication_name', sa.String(length=64), nullable=True))
    op.add_column('theses', sa.Column('publication_number', sa.String(length=64), nullable=True))
    op.add_column('theses', sa.Column('stu_academy', sa.String(length=64), nullable=True))
    op.add_column('theses', sa.Column('stu_class', sa.String(length=64), nullable=True))
    op.add_column('theses', sa.Column('stu_name', sa.String(length=64), nullable=True))
    op.add_column('theses', sa.Column('stu_number', sa.String(length=64), nullable=True))
    op.add_column('theses', sa.Column('stu_phone_number', sa.String(length=64), nullable=True))
    op.add_column('theses', sa.Column('stu_qq', sa.String(length=64), nullable=True))
    op.add_column('theses', sa.Column('thesis_name', sa.String(length=64), nullable=True))
    op.add_column('theses', sa.Column('weici', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('theses', 'weici')
    op.drop_column('theses', 'thesis_name')
    op.drop_column('theses', 'stu_qq')
    op.drop_column('theses', 'stu_phone_number')
    op.drop_column('theses', 'stu_number')
    op.drop_column('theses', 'stu_name')
    op.drop_column('theses', 'stu_class')
    op.drop_column('theses', 'stu_academy')
    op.drop_column('theses', 'publication_number')
    op.drop_column('theses', 'publication_name')
    op.drop_column('theses', 'filename')
    op.drop_column('theses', 'dangci')
    op.drop_column('theses', 'comment')
    op.create_foreign_key('competitions_ibfk_1', 'competitions', 'projects', ['project_id'], ['id'])
    ### end Alembic commands ###
