"""init

Revision ID: 972327f5fa84
Revises: 
Create Date: 2016-11-21 20:07:35.345878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '972327f5fa84'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('real_name', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('power', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('created_people', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_real_name'), 'accounts', ['real_name'], unique=False)
    op.create_index(op.f('ix_accounts_username'), 'accounts', ['username'], unique=True)
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academy', sa.String(length=64), nullable=True),
    sa.Column('company_name', sa.String(length=64), nullable=True),
    sa.Column('company_category', sa.String(length=64), nullable=True),
    sa.Column('legal_person_name', sa.String(length=64), nullable=True),
    sa.Column('legal_person_number', sa.String(length=64), nullable=True),
    sa.Column('legal_person_phone_number', sa.String(length=64), nullable=True),
    sa.Column('legal_person_qq', sa.String(length=64), nullable=True),
    sa.Column('legal_person_class', sa.String(length=64), nullable=True),
    sa.Column('register_addr', sa.String(length=64), nullable=True),
    sa.Column('register_capital', sa.String(length=64), nullable=True),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.Column('scope', sa.String(length=64), nullable=True),
    sa.Column('credit_code', sa.String(length=64), nullable=True),
    sa.Column('comment', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('create_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('other',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('created_people', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('theses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('achievement_name', sa.String(length=64), nullable=True),
    sa.Column('prize_category', sa.String(length=64), nullable=True),
    sa.Column('prize_level', sa.String(length=64), nullable=True),
    sa.Column('stu_name', sa.String(length=64), nullable=True),
    sa.Column('stu_phone_number', sa.String(length=64), nullable=True),
    sa.Column('stu_number', sa.String(length=64), nullable=True),
    sa.Column('stu_qq', sa.String(length=64), nullable=True),
    sa.Column('stu_class', sa.String(length=64), nullable=True),
    sa.Column('teacher_name', sa.String(length=64), nullable=True),
    sa.Column('teacher_title', sa.String(length=64), nullable=True),
    sa.Column('prize_date', sa.Date(), nullable=True),
    sa.Column('award_department', sa.String(length=64), nullable=True),
    sa.Column('sponsor', sa.String(length=64), nullable=True),
    sa.Column('comment', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('competitions')
    op.drop_table('theses')
    op.drop_table('projects')
    op.drop_table('patent')
    op.drop_table('other')
    op.drop_table('create_project')
    op.drop_table('company')
    op.drop_index(op.f('ix_accounts_username'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_real_name'), table_name='accounts')
    op.drop_table('accounts')
    ### end Alembic commands ###
