"""update for patent

Revision ID: b6b10c57992e
Revises: 8425c4ccc72a
Create Date: 2016-11-26 15:10:39.624344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6b10c57992e'
down_revision = '8425c4ccc72a'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patent', sa.Column('certificate_number', sa.String(length=64), nullable=True))
    op.add_column('patent', sa.Column('commet', sa.String(length=64), nullable=True))
    op.add_column('patent', sa.Column('date1', sa.String(length=64), nullable=True))
    op.add_column('patent', sa.Column('date2', sa.String(length=64), nullable=True))
    op.add_column('patent', sa.Column('filename', sa.String(length=64), nullable=True))
    op.add_column('patent', sa.Column('inventor', sa.String(length=64), nullable=True))
    op.add_column('patent', sa.Column('inventor_class', sa.String(length=64), nullable=True))
    op.add_column('patent', sa.Column('inventor_number', sa.String(length=64), nullable=True))
    op.add_column('patent', sa.Column('inventor_phone', sa.String(length=64), nullable=True))
    op.add_column('patent', sa.Column('inventor_qq', sa.String(length=64), nullable=True))
    op.add_column('patent', sa.Column('patent_categorg', sa.String(length=64), nullable=True))
    op.add_column('patent', sa.Column('patent_name', sa.String(length=64), nullable=True))
    op.add_column('patent', sa.Column('patent_number', sa.String(length=64), nullable=True))
    op.add_column('patent', sa.Column('patentee', sa.String(length=64), nullable=True))
    op.add_column('patent', sa.Column('stu_academy', sa.String(length=64), nullable=True))
    op.add_column('patent', sa.Column('weici', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patent', 'weici')
    op.drop_column('patent', 'stu_academy')
    op.drop_column('patent', 'patentee')
    op.drop_column('patent', 'patent_number')
    op.drop_column('patent', 'patent_name')
    op.drop_column('patent', 'patent_categorg')
    op.drop_column('patent', 'inventor_qq')
    op.drop_column('patent', 'inventor_phone')
    op.drop_column('patent', 'inventor_number')
    op.drop_column('patent', 'inventor_class')
    op.drop_column('patent', 'inventor')
    op.drop_column('patent', 'filename')
    op.drop_column('patent', 'date2')
    op.drop_column('patent', 'date1')
    op.drop_column('patent', 'commet')
    op.drop_column('patent', 'certificate_number')
    ### end Alembic commands ###
